More bugfixes
Script was trying to write the filesystem faster than the partition became available.

diff --git a/config/onxsd b/config/onxsd
--- a/config/onxsd
+++ b/config/onxsd
@@ -29,27 +29,38 @@ PARTITION_DISK () {
     echo "Partitioning and formatting $DISK."
     
     # Wipe filesystem signatures from disk.
-    wipefs -af "$DISK" && 
+    wipefs -af "$DISK" &&
         echo "Wiped filesystem signatures from $DISK." ||
         echo "Failed to wipe filesystem signatures from $DISK."
         
     # Create partition table on disk.
-    parted "$DISK" --script mktable gpt &&
-        echo "Wrote GUID Partition Table to $DISK." ||
-        (echo "Failed to write GUID Partition Table to $DISK."; return 1;)
-        
+    if parted "$DISK" --script mktable gpt; then
+        echo "Wrote GUID Partition Table to $DISK."
+    else
+        echo "Failed to write GUID Partition Table to $DISK."
+        return
+    fi
+    
     # Create partition on disk.
-    parted -a minimal "$DISK" --script mkpart primary ext4 1MiB 100% &&
-        echo "Created partition on $DISK." ||
-        (echo "Failed to create partition on $DISK."; return 1;)
-        
+    if parted -a minimal "$DISK" --script mkpart primary ext4 1MiB 100%; then
+        echo "Created partition on $DISK."
+    else
+        echo "Failed to create partition on $DISK."
+        return
+    fi
+    
+    sleep 3
+    
     # Write filesystem to partition.
-    mkfs.ext4 -F "$DISK}"1 &&
-        echo "Wrote ext4 filesystem to ${DISK}1." ||
-        (echo "Failed to write filesystem to ${DISK}1."; return 1;)
+    if mkfs.ext4 -F "$DISK"1; then
+        echo "Wrote ext4 filesystem to ${DISK}1."
+    else
+        echo "Failed to write filesystem to ${DISK}1."
+        return
+    fi
     
     local SERIAL=$(smartctl -ij $DISK | jq -r .'serial_number')
-    local UUID=$(blkid -s UUID -o value ${DISK}1)
+    local UUID=$(blkid -s UUID -o value "$DISK"1)
     
     if [ "$SERIAL" == "null" ]; then
         local MOUNTPOINT="/mnt/Media/$UUID"
@@ -59,12 +70,12 @@ PARTITION_DISK () {
     
     mkdir -p "$MOUNTPOINT"
     
-    echo "UUID=${UUID} ${MOUNTPOINT} auto defaults,nofail,errors=continue 0 0" &>> /etc/fstab
+    echo "UUID=${UUID} ${MOUNTPOINT} auto defaults,nofail,errors=continue 0 0" >> /etc/fstab
 }
 
 ALIGN_CHECK () {
     local DISK="$1"
-    local PART="$2"
+    local PART="1"
     parted "$DISK" --script align-check min "$PART"
 }
 
@@ -103,7 +114,7 @@ CHECK_DISK () {
         local PART=${PARTS[0]}
         local FS_TYPE=$(lsblk -f -n -o FSTYPE $PART)
         
-        if ! ALIGN_CHECK $DISK ${PARTS[0]}; then
+        if ! ALIGN_CHECK $DISK; then
             # If the partition is not properly aligned, repartition and format disk.
             PARTITION_DISK $DISK
         elif [ "$FS_TYPE" != "ext4" ]; then
@@ -147,3 +158,4 @@ done
 mount -av
 
 exit 0
+
